### ISSUE TITLE
previews problem

### ISSUE THREAD

**Issue by JoseConseco** [luukvbaal/nnn.nvim#18]
Hi,  I just installed nnn and previews-tui.
It works ok if I run in console (alacritty) :  
`tmux new-session` 
and then 
`nnn -P <preview_key>`   (it is not updating preview when navigating files thought)
The real problem is when i runs above as single command: 
`tmux new-session nnn -P <preview_key>`
Then nnn previews-tui is complaining about missing env :
![image](https://user-images.githubusercontent.com/13521338/140659883-a2005cc9-b302-49be-a6f5-02446ca425be.png)
Same story when running above command from nnn.nvim .  Any ideas why joined command gives error, while run in sequence it works almost ok (well except previews not updating when navigating file)  ?

**Comment by luukvbaal** [comment]
The issue is that the proper FIFO env variable is `NNN_FIFO`, not `NNN_PREVIEW` as seems to be the case in your version of `preview-tui`. Where did you get this version, seems like you replaced `NNN_FIFO` with `NNN_PREVIEW` in the script? 

Please try with the latest version of `preview-tui` from [nnn repo](https://github.com/jarun/nnn/blob/master/plugins/preview-tui).

**Comment by JoseConseco** [comment]
the latest version worked ok.  The previews version I got was from some [nnn issue report reply](https://github.com/jarun/nnn/issues/1206#issuecomment-950253315).  I was also messing with  tmux env variables and such like it was described in [here](https://stackoverflow.com/a/66531282/13588868).  Its seems the NNN_PREVIEW is not needed after all.  Thanks for the help and great plugin!
