### ISSUE TITLE
Everytime i open the Picker or Explorer, the galaxyline disappears

### ISSUE THREAD

**Issue by hrqmonteiro** [luukvbaal/nnn.nvim#28]
Man, it is just not usable this way.

I tried using the plugin again, after many months (when i installed the last time it was like this), and the same behavior happens:

https://user-images.githubusercontent.com/17055027/144287716-3d4f24a5-31e6-4abe-ae5f-bc01172bdaf4.mp4

**Comment by luukvbaal** [comment]
This plugin does not touch the status line, nor am I familiar with it's inner workings. I'm afraid you'll have to open an issue on galaxyline issue tracker instead.

Like I said last time, the issue is not present for me on feline so there must be something galaxyline can do about it.

**Comment by luukvbaal** [comment]
It's best if you provide a minimal reproducible config if you want plugin developer to look into your issue...

**Comment by luukvbaal** [comment]
I installed a random galaxyline config and couldn't reproduce the issue... There's no way for me to look into this if you don't share your config.

**Comment by luukvbaal** [comment]
I was able to reproduce the issue with the config found in your dotfiles. `:setl statusline` yields

    statusline=%=

in the situation from your gif. Again, this plugin does not touch the statusline so I suggest you open an issue with galaxyline instead.

**Comment by luukvbaal** [comment]
The issue is that galaxyline relies on `autocmd` events to refresh the statusline. Specifically the `WinEnter` or `BufEnter` events should fire when closing the `nnn` window but for some reason that doesn't happen when closing `nnn` with <kbd>q</kbd>.

I could add a workaround but this seems to be a bug in neovim to me. Perhaps something to do with `autocmd`s not firing during an `on_exit` callback.
