### ISSUE TITLE
some quick thoughts on some implementations

### ISSUE THREAD

**Issue by haolian9** [luukvbaal/nnn.nvim#73]
hi! sorry to open an issue with one vague title. i just discovered this plugin, i really like its writing style.
though i had some doubts on its some impl, i hope you dont mind i putting these rough thoughts here.

* tmpdir is not per nvim instance nor per user, this line has a race condition
    ```
    io.open(tmpdir .. "/nnn-preview-tui-posoffset", "w")
    ```
* TERM: fwik termopen will ignore TERM env and set it to xterm-256color, so set a different TERM to nnn, i think that could lead to unknown problem
* `tabe|NnnExplorer` will run nnn in full screen mode, no tabline and statusline showed.
  is that intended?
* opening NnnExplorer in different tab will create multiple nnn instance by default.
  is that intended? since nnn already has the tab feature, IMO there is an overlap on functionality. 

(since i have not used this plugin for a long time, my thoughts could be naive, sorry about that)

**Comment by luukvbaal** [comment]
Hey, thanks for sharing your thoughts and kind words.

> tmpdir is not per nvim instance nor per user, this line has a race condition

Yes, ideally we would append the process id of the nnn instance to to file name (as done for other preview-tui tmpfiles), but I'm not sure if/how we can determine the PID of the nnn instance we start with `termopen()`.

> TERM: fwik termopen will ignore TERM env and set it to xterm-256color, so set a different TERM to nnn, i think that could lead to unknown problem

I'm not sure about the internals but passing along `TERM` was necessary for mouse support. Without it clicking wouldn't work, so I don't think it's ignored.

> tabe|NnnExplorer will run nnn in full screen mode, no tabline and statusline showed.
is that intended?

Yes, nnn is intentionally made fullscreen when it is the only window in a tabpage. Haven't had complaints so far but we could make it configurable if desired.

> opening NnnExplorer in different tab will create multiple nnn instance by default.
is that intended? since nnn already has the tab feature, IMO there is an overlap on functionality.

This is intended and configurable with [`cfg.explorer.tabs`](https://github.com/luukvbaal/nnn.nvim/blob/17f05c306e6906b4b6cd477e603697fd352960e8/README.md?plain=1#L87).

**Comment by haolian9** [comment]
thanks for your reply!

> determine the PID of the nnn instance we start with termopen()

i think it is jobpid: `:echo jobpid(termopen('sleep 1'))`

i'll check the use of `TERM` further. yeah, the last two behaviors are fine to me.

**Comment by haolian9** [comment]
hi, i tried to use nnn.nvim in konsole and xterm, the mouse is not working in my tests.
though i think that's a problem on nnn side.

**Comment by luukvbaal** [comment]
> i think it is jobpid: :echo jobpid(termopen('sleep 1'))

Thanks, that works. But `io.open(tmpdir .. "/nnn-preview-tui-posoffset", "w")` is used for image preview offset with ueberzug in a tmux session, which complicates things. The actual PID is equal to `jobpid(cmd) + 1` on my end. I guess we can loop over `jobpid(cmd) + {1...10}` or something and check that the running process is `nnn`.
